import PDFDocument from 'pdfkit'
import type { InventoryItemRow } from '@ocg/db'
import { inventoryBreadcrumb } from './inventoryTaxonomy'
import { normalizeDisplayNomenclature } from './inventoryPresentation'

export interface InventoryPdfInput {
  company: string
  brand: string
  items: InventoryItemRow[]
  classifications: string[]
  family: string
  generatedBy: string
  generatedAt: Date
}

/** A controlled server-side export of exactly the already-authorised current
 * view supplied by the route. It deliberately accepts no unfiltered dataset. */
export async function createInventoryPdf(input: InventoryPdfInput): Promise<Buffer> {
  const doc = new PDFDocument({
    size: 'A4',
    margin: 42,
    info: { Title: `${input.brand} inventory current view` },
  })
  const chunks: Buffer[] = []
  doc.on('data', (chunk: Buffer) => chunks.push(chunk))
  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)
  })

  const navy = '#1a1a2e'
  const gold = '#b07a00'
  doc.fillColor(gold).font('Helvetica-Bold').fontSize(9).text(input.company.toUpperCase(), { characterSpacing: 1.4 })
  doc.fillColor(navy).fontSize(20).text(`${input.brand} Inventory`)
  doc.fillColor('#667085').font('Helvetica').fontSize(9).text('CURRENT FILTERED VIEW')
  doc.moveDown(0.6)
  const filters = [
    input.classifications.length ? `Classifications: ${input.classifications.join(', ')}` : 'Classifications: All',
    input.family ? `Product family: ${input.family}` : 'Product family: All',
  ]
  doc.fillColor('#344054').fontSize(9).text(filters.join('   |   '))
  doc.text(`As of: ${input.generatedAt.toLocaleDateString('en-KE', { timeZone: 'Africa/Nairobi' })}   |   Generated: ${input.generatedAt.toLocaleString('en-KE', { timeZone: 'Africa/Nairobi' })}`)
  doc.text(`Generated by: ${input.generatedBy}`)
  doc.moveDown(0.8)

  const totals = new Map<string, number>()
  let totalValue = 0
  for (const item of input.items) {
    const unit = item.base_unit || item.unit || 'unit'
    totals.set(unit, (totals.get(unit) ?? 0) + Number(item.quantity))
    totalValue += Number(item.quantity) * Number(item.unit_value_ksh)
  }
  doc.roundedRect(42, doc.y, 511, 42, 5).fill('#F8F9FB')
  const summaryY = doc.y + 11
  doc.fillColor(navy).font('Helvetica-Bold').fontSize(10).text(`${input.items.length} items`, 54, summaryY)
  doc.font('Helvetica').fontSize(9).text([...totals].map(([unit, quantity]) => `${formatNumber(quantity)} ${unit}`).join('  |  ') || 'No quantity', 150, summaryY, { width: 250 })
  doc.font('Helvetica-Bold').text(`Ref value KSh ${formatNumber(totalValue)}`, 410, summaryY, { width: 130, align: 'right' })
  doc.y = summaryY + 38

  let pageNumber = 1
  drawHeader(doc)
  if (input.items.length === 0) {
    doc.fillColor('#667085').font('Helvetica').fontSize(10).text('No inventory items match the applied filters.', 48, doc.y + 12)
  }
  for (const item of input.items) {
    if (doc.y > 745) {
      pageFooter(doc, pageNumber)
      doc.addPage()
      pageNumber += 1
      drawHeader(doc)
    }
    const y = doc.y + 7
    const name = normalizeDisplayNomenclature(item.display_name || item.name)
    doc.fillColor(navy).font('Helvetica-Bold').fontSize(8.5).text(name, 48, y, { width: 145 })
    doc.fillColor('#667085').font('Helvetica').fontSize(7).text(item.sku || 'No SKU', 48, y + 12, { width: 145 })
    doc.fillColor('#344054').fontSize(7.8).text(inventoryBreadcrumb(item), 200, y, { width: 150, height: 25 })
    doc.text(`${formatNumber(Number(item.quantity))} ${item.item_type === 'packaging' ? 'pcs' : item.base_unit || item.unit}`, 357, y, { width: 65, align: 'right' })
    doc.text(`KSh ${formatNumber(Number(item.unit_value_ksh))}`, 430, y, { width: 55, align: 'right' })
    doc.text(`KSh ${formatNumber(Number(item.quantity) * Number(item.unit_value_ksh))}`, 492, y, { width: 55, align: 'right' })
    doc.moveTo(48, y + 29).lineTo(547, y + 29).strokeColor('#EAECF0').stroke()
    doc.y = y + 30
  }
  pageFooter(doc, pageNumber)
  doc.end()
  return done
}

function drawHeader(doc: PDFKit.PDFDocument) {
  const y = doc.y
  doc.rect(42, y, 511, 22).fill('#1a1a2e')
  doc.fillColor('#FFFFFF').font('Helvetica-Bold').fontSize(7.5)
  doc.text('ITEM', 48, y + 7, { width: 145 })
  doc.text('CLASSIFICATION', 200, y + 7, { width: 150 })
  doc.text('ON HAND', 357, y + 7, { width: 65, align: 'right' })
  doc.text('REF COST', 430, y + 7, { width: 55, align: 'right' })
  doc.text('VALUE', 492, y + 7, { width: 55, align: 'right' })
  doc.y = y + 22
}

function pageFooter(doc: PDFKit.PDFDocument, pageNumber: number) {
  doc.fillColor('#98A2B3').font('Helvetica').fontSize(7)
    .text(`Page ${pageNumber} | Controlled current-view export`, 42, 784, { width: 511, align: 'center' })
}

function formatNumber(value: number) {
  return value.toLocaleString('en-KE', { maximumFractionDigits: 3 })
}
