'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { ShieldAlert, X } from 'lucide-react'
import { api } from '@/lib/apiClient'

interface Option { id: string; label: string; brandId?: string; unit?: string; itemType?: string }
interface IncidentOption extends Option { status: string; disposition: string; itemId: string | null; batch: string }

type Mode = 'report' | 'review' | 'dispose' | 'recover'

export function QualityIncidentPanel({ brands, items, incidents, runs, canReview }: {
  brands: Option[]
  items: Option[]
  incidents: IncidentOption[]
  runs: Option[]
  canReview: boolean
}) {
  const router = useRouter()
  const [open, setOpen] = useState(false)
  const [mode, setMode] = useState<Mode>('report')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [message, setMessage] = useState('')
  const [report, setReport] = useState({ brand_id: brands[0]?.id ?? '', item_id: '', batch_number: '', custody_type: 'production', affected_quantity: '', unit: '', reason_category: '', description: '' })
  const [review, setReview] = useState({ incident_id: incidents[0]?.id ?? '', disposition: 'rework', disposition_note: '' })
  const [disposal, setDisposal] = useState({ quality_incident_id: '', quantity: '', custody_state: 'quality_hold', reason: '', valuation_basis: 'current_reference_cost' })
  const [recovery, setRecovery] = useState({ production_run_id: '', quality_incident_id: '', source_item_id: '', source_batch_number: '', component_item_id: '', component_kind: 'bottle', quantity: '', unit: 'pcs', condition_status: 'reusable', notes: '' })

  const selectedItem = items.find((item) => item.id === report.item_id)
  const disposalIncident = incidents.find((incident) => incident.id === disposal.quality_incident_id)

  async function submit(body: Record<string, unknown>, success: string) {
    setBusy(true); setError(''); setMessage('')
    const result = await api<{ error?: string }>('/api/manufacturing', { method: 'POST', body: JSON.stringify(body) })
    setBusy(false)
    if (!result.ok) { setError(result.data.error ?? 'The action could not be saved.'); return }
    setMessage(success)
    router.refresh()
  }

  if (!open) return <button onClick={() => setOpen(true)} className="inline-flex items-center gap-2 rounded-lg border border-amber-200 bg-amber-50 px-4 py-2 text-sm font-medium text-amber-800 hover:bg-amber-100"><ShieldAlert size={15} /> Quality incident</button>

  return <section className="rounded-xl border border-amber-100 bg-white p-5 shadow-sm">
    <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-ocg-gold">Quality / stock incident</p><p className="mt-1 text-sm text-gray-500">Incident authority and custody events stay separate. Quantities are never edited away.</p></div><button onClick={() => setOpen(false)} aria-label="Close" className="rounded p-1 text-gray-400 hover:text-gray-700"><X size={17} /></button></div>
    <div className="mt-4 flex flex-wrap gap-2"><ModeButton active={mode === 'report'} onClick={() => setMode('report')}>Report incident</ModeButton>{canReview ? <><ModeButton active={mode === 'review'} onClick={() => setMode('review')}>Approve disposition</ModeButton><ModeButton active={mode === 'dispose'} onClick={() => setMode('dispose')}>Post disposal</ModeButton></> : null}<ModeButton active={mode === 'recover'} onClick={() => setMode('recover')}>Recovered packaging</ModeButton></div>

    {mode === 'report' ? <div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Field label="Brand"><select className="input" value={report.brand_id} onChange={(event) => setReport({ ...report, brand_id: event.target.value })}>{brands.map((brand) => <option key={brand.id} value={brand.id}>{brand.label}</option>)}</select></Field><Field label="Item / SKU"><select className="input" value={report.item_id} onChange={(event) => { const item = items.find((candidate) => candidate.id === event.target.value); setReport({ ...report, item_id: event.target.value, brand_id: item?.brandId ?? report.brand_id, unit: item?.unit ?? report.unit }) }}><option value="">Select…</option>{items.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></Field><Field label="Batch"><input className="input" value={report.batch_number} onChange={(event) => setReport({ ...report, batch_number: event.target.value })} /></Field><Field label="Current custody"><select className="input" value={report.custody_type} onChange={(event) => setReport({ ...report, custody_type: event.target.value })}><option value="production">Production</option><option value="quality_hold">Quality hold</option><option value="finished_goods_store">Finished Goods Store</option><option value="field_sales">Field Sales</option><option value="raw_store">Raw Store</option><option value="packaging_store">Packaging Store</option></select></Field><Field label={`Affected quantity${selectedItem?.unit ? ` (${selectedItem.unit})` : ''}`}><input type="number" min="0" step="any" className="input" value={report.affected_quantity} onChange={(event) => setReport({ ...report, affected_quantity: event.target.value })} /></Field><Field label="Reason category"><select className="input" value={report.reason_category} onChange={(event) => setReport({ ...report, reason_category: event.target.value })}><option value="">Select…</option>{['Defective manufactured product','Damaged finished goods','Contamination','Packaging failure','Incorrect packaging','Recall','Spoilage','Rework required','Disposal required'].map((reason) => <option key={reason}>{reason}</option>)}</select></Field><label className="block md:col-span-2"><span className="mb-1 block text-xs font-medium text-gray-500">Description</span><textarea className="input min-h-20" value={report.description} onChange={(event) => setReport({ ...report, description: event.target.value })} /></label></div> : null}

    {mode === 'review' ? <div className="mt-4 grid gap-3 md:grid-cols-3"><Field label="Incident"><select className="input" value={review.incident_id} onChange={(event) => setReview({ ...review, incident_id: event.target.value })}><option value="">Select…</option>{incidents.filter((incident) => ['reported', 'under_review'].includes(incident.status)).map((incident) => <option key={incident.id} value={incident.id}>{incident.label}</option>)}</select></Field><Field label="Approved disposition"><select className="input" value={review.disposition} onChange={(event) => setReview({ ...review, disposition: event.target.value })}><option value="release">Release / no action</option><option value="quarantine">Quarantine</option><option value="return_to_production">Return to Production</option><option value="rework">Rework</option><option value="repackage">Repackage</option><option value="partial_salvage">Partial salvage</option><option value="dispose">Dispose / write off</option></select></Field><Field label="Disposition rationale"><input className="input" value={review.disposition_note} onChange={(event) => setReview({ ...review, disposition_note: event.target.value })} /></Field></div> : null}

    {mode === 'dispose' ? <div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Field label="Approved disposal incident"><select className="input" value={disposal.quality_incident_id} onChange={(event) => setDisposal({ ...disposal, quality_incident_id: event.target.value })}><option value="">Select…</option>{incidents.filter((incident) => incident.status === 'disposition_approved' && ['dispose', 'partial_salvage'].includes(incident.disposition)).map((incident) => <option key={incident.id} value={incident.id}>{incident.label}</option>)}</select></Field><Field label={`Quantity${disposalIncident?.unit ? ` (${disposalIncident.unit})` : ''}`}><input className="input" type="number" min="0" step="any" value={disposal.quantity} onChange={(event) => setDisposal({ ...disposal, quantity: event.target.value })} /></Field><Field label="Production state"><select className="input" value={disposal.custody_state} onChange={(event) => setDisposal({ ...disposal, custody_state: event.target.value })}><option value="quality_hold">Quality hold</option><option value="rework">Rework</option><option value="bulk_wip">Bulk / WIP</option><option value="packaged_output">Packaged output</option><option value="materials">Materials</option><option value="packaging">Packaging</option></select></Field><Field label="Reason"><input className="input" value={disposal.reason} onChange={(event) => setDisposal({ ...disposal, reason: event.target.value })} /></Field><p className="text-xs text-gray-500 md:col-span-2 lg:col-span-4">The current reference cost is used as the valuation basis. Posting creates an outward custody event and a linked operational loss record atomically.</p></div> : null}

    {mode === 'recover' ? <div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Field label="Rework / recovery run"><select className="input" value={recovery.production_run_id} onChange={(event) => setRecovery({ ...recovery, production_run_id: event.target.value })}><option value="">Select…</option>{runs.map((run) => <option key={run.id} value={run.id}>{run.label}</option>)}</select></Field><Field label="Linked incident"><select className="input" value={recovery.quality_incident_id} onChange={(event) => setRecovery({ ...recovery, quality_incident_id: event.target.value })}><option value="">Optional</option>{incidents.map((incident) => <option key={incident.id} value={incident.id}>{incident.label}</option>)}</select></Field><Field label="Source product"><select className="input" value={recovery.source_item_id} onChange={(event) => setRecovery({ ...recovery, source_item_id: event.target.value })}><option value="">Optional</option>{items.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></Field><Field label="Source batch"><input className="input" value={recovery.source_batch_number} onChange={(event) => setRecovery({ ...recovery, source_batch_number: event.target.value })} /></Field><Field label="Recovered component"><select className="input" value={recovery.component_item_id} onChange={(event) => setRecovery({ ...recovery, component_item_id: event.target.value })}><option value="">Select packaging…</option>{items.filter((item) => item.itemType === 'packaging').map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></Field><Field label="Component kind"><select className="input" value={recovery.component_kind} onChange={(event) => setRecovery({ ...recovery, component_kind: event.target.value })}>{['bottle','container','closure','cap','pump','front_sticker','back_sticker','other'].map((kind) => <option key={kind}>{kind.replace(/_/g, ' ')}</option>)}</select></Field><Field label="Quantity (pcs)"><input className="input" type="number" min="0" step="any" value={recovery.quantity} onChange={(event) => setRecovery({ ...recovery, quantity: event.target.value })} /></Field><Field label="Condition"><select className="input" value={recovery.condition_status} onChange={(event) => setRecovery({ ...recovery, condition_status: event.target.value })}><option value="reusable">Reusable</option><option value="damaged">Damaged / quality hold</option><option value="quarantined">Quarantined</option></select></Field><Field label="Notes"><input className="input" value={recovery.notes} onChange={(event) => setRecovery({ ...recovery, notes: event.target.value })} /></Field><p className="text-xs text-gray-500 md:col-span-2 lg:col-span-4">Reusable pieces remain in Production. Damaged or quarantined pieces remain on Quality hold; use an approved disposal action to write off any residue.</p></div> : null}

    {error ? <p className="mt-3 rounded-lg bg-red-50 p-2.5 text-sm text-red-600">{error}</p> : null}{message ? <p className="mt-3 rounded-lg bg-emerald-50 p-2.5 text-sm text-emerald-700">{message}</p> : null}
    <button disabled={busy} onClick={() => {
      if (mode === 'report') return submit({ action: 'create-quality-incident', ...report, affected_quantity: Number(report.affected_quantity), unit: report.unit || selectedItem?.unit || '' }, 'Quality incident reported. No stock moved.')
      if (mode === 'review') return submit({ action: 'approve-quality-disposition', ...review }, 'Disposition approved. Post the matching custody action next.')
      if (mode === 'dispose') return submit({ action: 'dispose-production-custody', ...disposal, item_id: disposalIncident?.itemId, batch_number: disposalIncident?.batch, unit: disposalIncident?.unit, quantity: Number(disposal.quantity), idempotency_key: crypto.randomUUID() }, 'Approved disposal posted with valued loss history.')
      return submit({ action: 'record-recovered-packaging', ...recovery, quality_incident_id: recovery.quality_incident_id || null, source_item_id: recovery.source_item_id || null, quantity: Number(recovery.quantity), idempotency_key: crypto.randomUUID() }, 'Recovered packaging classified. Reusable/quarantined pieces remain visible in Production custody.')
    }} className="mt-4 rounded-lg bg-ocg-navy px-5 py-2 text-sm font-medium text-white disabled:opacity-60">{busy ? 'Saving…' : mode === 'report' ? 'Report incident' : mode === 'review' ? 'Approve disposition' : mode === 'dispose' ? 'Post custody out + loss' : 'Record recovered packaging'}</button>
  </section>
}

function ModeButton({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button onClick={onClick} className={`rounded-full px-3 py-1.5 text-xs font-medium ${active ? 'bg-ocg-navy text-white' : 'bg-gray-100 text-gray-500'}`}>{children}</button> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1 block text-xs font-medium text-gray-500">{label}</span>{children}</label> }
